baseURL = 'http://trigomijes.com/'
languageCode = 'en-us'
title = 'hobby blog'
theme = 'poison'


[params]
brand = "Frank"
dateFormat = "2006-01-02"
favicon = "favicon.png"
brand_image = "favicon.png"
description = "This is description"
dark_mode = true
rss_icon = true
menu = [
	{Name = "About", URL = "/about/", HasChildren = false},
	{Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
]
email_url = "mailto://blog@trigomijes.com"
github_url = "https://github.com/franciscotrigo"
linkedin_url = "https://www.linkedin.com/in/francisco-trigo-mijes/"

