baseURL: https://trigomijes.com/ # Replace with your domain
languageCode: en-us
theme: smigle
title: Francisco TrigoMijes
taxonomies:
  tag: tags
  category: categories
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
module:
  mounts:
    - source: assets
      target: assets
    - source: assets
      target: assets/images
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "Francisco TrigoMijes"
  brandIconFile: "favicon.ico"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: GitHub
      url: https://github.com/franciscotrigo
    - name: LinkedIn
      url: https://linkedin.com/in/francisco-trigo-mijes
    - name: Email
      url: mailto://blog@trigomijes.com
    - name: RSS
      url: https://trigomijes.com/posts/index.xml

  subtitle: "IT Professional"
